### ISSUE TITLE
Ripple effect not working when defaultColor is set to transparent

### ISSUE THREAD

**Issue by ugurcany** [medyo/Fancybuttons#49]
Ripple effect feature that comes with the version 1.6 is not working when we set the `fb_defaultColor` to `@android:color/transparent`. In other words, the color to which we set `fb_focusColor`, has no effect if default color is transparent. Previous versions do not have such problem. In v1.5, even if default color is set to transparent, focus color has still an effect.

Could you please solve this problem that occurs in v1.6?

**Comment by medyo** [comment]
Hi @ugurcany,

Normally `fb_defaultColor` is made to host a 'Visible' color, if you're trying to have a transparent background with a border color, use the tag `fb_ghost`

**Comment by ugurcany** [comment]
I set `fb_ghost` to `true`, but nothing changed. My button does not have border color by the way.

**Comment by medyo** [comment]
I'm using right now `fb_ghost` on a new project and it works perfectly, please check if you've done all necessary attributes like `fb_borderWidth` and `fb_borderColor` ...

**Comment by ugurcany** [comment]
My button has **no ** border. For what does `fb_ghost` exist? I don't get its purpose. What is it doing?

**Comment by medyo** [comment]
`fb_ghost` needs a border to work perfectly, If it's defined the focus state will be applied to it instead of button background. Please run the sample project to figure out more : https://github.com/medyo/Fancybuttons#demo-application--download-apk

**Edit:**
I just tested with a transparent color and you're right, Ripple effect seems not working. 
While waiting for a fix, you could hack it by using the same color as your background, like `fb_defaultColor="@android:color/white"` if your background is white.

**Comment by ugurcany** [comment]
Thanks. I am using that workaround right now. Waiting for a fix.

**Comment by medyo** [comment]
This issue is now fixed, thanks to @sushant23
